name: mean-shift-for-SSL-2
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - python-dateutil
  - python-flatbuffers
  - pytorch
  - torchvision
  - faiss-gpu
